### ISSUE TITLE
Incompatible with jade

### ISSUE THREAD

**Issue by naturalethic** [n33/skel#136]
I've got a pull request with the jade project to allow % in class names, but I did that before also realizing skel needs to have parens ( ).  I'm not sure that it's really possible to allow parens in jade.  I wanted to just mention this here in a ticket in case you had any ideas.  If skel were to use say, brackets [ ] instead of parens, that could be made compatible with jade.

Here's the PR with my comments:
https://github.com/jadejs/jade/pull/1958

**Comment by n33** [comment]
In case you're wondering, I actually went with the weird-ish class names for three reasons:

1. Class names should ideally be semantic (see https://css-tricks.com/semantic-class-names/), and as grid system classes are inherently non-semantic (and grid systems themselves a sort of sub-optimal hack anyway), I wanted to make that distinction absolutely clear. That way, if you have something ilke:

```
<article class="post 6u 12u(small)">
```

It's immediately evident which classes are semantic (`content`) and which aren't (`6u 12u(small)`).

2. They're short, concise, and (IMO) much easier to use than some of the alternatives out there.

3. Almost a 0% chance of there being a class conflict, because mine are just so ... weird.

That said, there's not too much I can do about this. The positions of the folks discussing the issue you opened over at jade are certainly valid (although the grid classes, etc. aren't meant to be edited so I'm not sure that's as big of a deal), and I'm intent on continuing to use these classes for the life of the grid system (which, given how awesome flexbox is, probably won't be for that long anyway :)

**Comment by n33** [comment]
Woops, I should have mentioned this:

If you're using Skel.scss (`_skel.scss`) on a project and you're familiar with Sass, it shouldn't take too much to change its classes to something compatible with jade (since they're all generated with a handful of mixins).
