### ISSUE TITLE
Layers & other features implementations in v3?

### ISSUE THREAD

**Issue by jmalatia** [n33/skel#140]
Is there a Layers (Panels) Implementation in version 3 like there was in the previous skel versions?  skel.lock?  skel.lock.permanent? If not, any plans to add them back?

**Comment by n33** [comment]
Layers = For now, probably not. Much of what it did can now be handled with CSS3 alone and a tiny bit of JS (as is the case with Baseline: https://github.com/n33/baseline).

Lock = Possibly as part of the Viewport module, since viewport meta tag manipulation is more or less how lock() was able to do its thing.
